Address:
    type: entity
    table: address
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        city:
            type: string
            nullable: false
            length: 200
            fixed: false
        state:
            type: string
            nullable: false
            length: 2
            fixed: false
        country:
            type: string
            nullable: true
            length: 200
            fixed: false
            default: Brazil
        zip:
            type: string
            nullable: false
            length: 45
            fixed: false
        street:
            type: string
            nullable: false
            length: 300
            fixed: false
        district:
            type: string
            nullable: false
            length: 200
            fixed: false
        number:
            type: integer
            nullable: true
            unsigned: false
        complement:
            type: string
            nullable: true
            length: 300
            fixed: false
    lifecycleCallbacks: {  }
