BarberHasUserSystem:
    type: entity
    table: barber_has_user_system
    indexes:
        fk_barber_has_user_system_user_system1_idx:
            columns:
                - user_system_id
        fk_barber_has_user_system_barber1_idx:
            columns:
                - barber_id
        fk_barber_has_user_system_user_role1_idx:
            columns:
                - user_role_id
    id: {  }
    oneToOne:
        barber:
            targetEntity: Barber
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                barber_id:
                    referencedColumnName: id
            orphanRemoval: false
        userSystem:
            targetEntity: UserSystem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_system_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        userRole:
            targetEntity: UserRole
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_role_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
