Service:
    type: entity
    table: service
    indexes:
        fk_service_barber1_idx:
            columns:
                - barber_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 200
            fixed: false
    manyToOne:
        barber:
            targetEntity: Barber
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                barber_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
