Service:
    type: entity
    table: service
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 200
            fixed: false
    manyToMany:
        barber:
            targetEntity: Barber
            cascade: {  }
            mappedBy: service
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
