# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    my.oauth_aware.user_provider.service:
        class: AppBundle\Service\User\UserAuthorizationService
        arguments: ["@doctrine.orm.entity_manager"]
    address_service:
        class: AppBundle\Service\Address\AddressService
        arguments: ["@doctrine.orm.entity_manager"]
    barber_service:
        class: AppBundle\Service\Barber\BarberService
        arguments: ["@doctrine.orm.entity_manager", "@address_service"]
    barber_schedule_service:
        class: AppBundle\Service\Barber\BarberScheduleService
        arguments: ["@doctrine.orm.entity_manager"]